services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'trainroutes'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'slaptai'
      MYSQL_ROOT_PASSWORD: 'verysecretpassword'
    ports:
      - 3306:3306
    expose:
      - 3306
